### ISSUE TITLE
fritakAGP - refusjon gravid og kronisk

### ISSUE THREAD

**Issue by laukvik** [navikt/fritakagp#134]
jsonfeltet "antallDager" vises ikke i journalpost eller på oppgaven i gosys. Dette gjør det vanskelig for saksbehandler å finne ut av om beregnet refusjon er riktig. Feltet kan hete: "Antall lønnsdager" i oppgave og på journalpost.

**Comment by maccyber** [comment]
![image](https://user-images.githubusercontent.com/701351/154003535-721dfd67-ada2-4dc5-9c01-7b80d8302d79.png)
![image](https://user-images.githubusercontent.com/701351/154003574-603650c2-9560-40ff-a35d-9d425281c74c.png)
